export const SEED_PRODUCTS = [
  {
    id: 1,
    title: "Personalized Name Bracelet – Custom Beaded Friendship Jewelry & Party Favor",
    category: "name_bracelets",
    price: 5.0,
    originalPrice: 7.0,
    description: "Bulk friendship bracelets for parties, birthdays, and team gifts. Personalized name bracelets, handmade with colorful beads for kids or group events. Celebrate every moment with custom beaded bracelets, perfect for kids’ birthdays, party favors, school events, and team gifts. Each bracelet is handmade to order and can be personalized with names or ",
    image: "https://i.etsystatic.com/53294188/r/il/e40b09/6528825481/il_fullxfull.6528825481_bfgh.jpg",
    image2: "https://i.etsystatic.com/53294188/r/il/f21c65/6480722116/il_fullxfull.6480722116_2b9b.jpg",
    colors: ["Indigo", "Purple", "Magenta", "Fuchsia", "Coral", "Barbie Pink", "Trend Pink", "Pink", "Cream", "Light Pink", "Light Yellow", "Lemon", "Yellow", "Peanut Green", "Green"],
    sizes: ["6 inches", "6.5 inches", "7 inches", "7.5 inches", "8 inches"],
    minOrder: 1,
    maxOrder: 5000,
  },
  {
    id: 2,
    title: "Custom Logo Beaded Bracelets – Personalized Bulk Gifts for Companies & Corporate Events",
    category: "corporate",
    price: 5.0,
    originalPrice: 7.0,
    description: "Custom Logo Beaded Bracelet – Personalized Jewelry for Every Occasion Showcase your brand, team, or school spirit with our custom beaded bracelets featuring a personalized brass logo charm! These bulk bracelets are perfect for corporate gifts, team events, universities, and fundraising. Whether you're looking for a name bracelet, friendship bracele",
    image: "https://i.etsystatic.com/53294188/r/il/b767ee/7743372955/il_fullxfull.7743372955_1qco.jpg",
    image2: "https://i.etsystatic.com/53294188/r/il/f5550e/6816181861/il_fullxfull.6816181861_fser.jpg",
    colors: ["White", "Black", "Yellow", "Lemon", "Amber", "Orange", "Cream", "Powder Pink", "Light Pink", "Lilac", "Puprle", "Dark Purple", "Red", "Dark Red", "Pink"],
    sizes: ["6 inches", "6.5 inches", "7 inches", "7.5 inches", "8 inches"],
    minOrder: 1,
    maxOrder: 5000,
  },
  {
    id: 3,
    title: "Custom Beaded Phone Charm – Personalized Name Strap, Kawaii Phone Lanyard, Tech Accessory Gift",
    category: "phone_charms",
    price: 15.99,
    originalPrice: 22.39,
    description: "Custom kawaii phone charm made with pastel beads and name letters perfect for cute phone straps, party favors, bulk gifts, and personalized accessories Create Your Own Personalized Phone Charm Aesthetic pastel beads + custom name letters create the cutest kawaii phone strap perfect for everyday use party favors and personalized tech accessories you",
    image: "https://i.etsystatic.com/53294188/r/il/e6ba6b/7466106725/il_fullxfull.7466106725_34oe.jpg",
    image2: "https://i.etsystatic.com/53294188/r/il/9160ad/7057127616/il_fullxfull.7057127616_tmw2.jpg",
    colors: [],
    sizes: ["6 inches", "6.5 inches", "7 inches", "7.5 inches", "8 inches"],
    minOrder: 1,
    maxOrder: 5000,
  },
  {
    id: 4,
    title: "Wood Bead Bracelet | Personalized Name | Natural Eco Handmade | Birthday Gift for Him",
    category: "eco_friendly",
    price: 5.0,
    originalPrice: 7.0,
    description: "Celebrate connection, style, and meaningful moments with this modern custom bracelet designed for everyday wear. This piece blends the look of elegant personalized jewelry with the charm of a classic friendship bracelet, creating a versatile accessory that feels both stylish and personal. Each bracelet can be customized to create a unique custom na",
    image: "https://i.etsystatic.com/53294188/r/il/a324bd/7695585014/il_fullxfull.7695585014_3xat.jpg",
    image2: "https://i.etsystatic.com/53294188/r/il/16b05b/7695587432/il_fullxfull.7695587432_a4vf.jpg",
    colors: ["White", "Yellow", "Orange", "Red", "Powder Pink", "Lila", "Cherry Rot", "Purple", "Turquoise 1", "Turquoise 2", "Baby Blue", "Blue", "Midnight Blue", "Olive", "Khaki Green"],
    sizes: ["6 inches", "6.5 inches", "7 inches", "7.5 inches", "8 inches"],
    minOrder: 1,
    maxOrder: 5000,
  },
  {
    id: 5,
    title: "Custom Name Beaded Bracelets – Personalized Team Friendship Jewelry Gifts in Bulk",
    category: "name_bracelets",
    price: 15.99,
    originalPrice: 22.39,
    description: "Celebrate unity with our Custom Friendship Bracelets! Available in bulk quantities of 1, 25, 100, or 1000, these personalized name bracelets are perfect for team events, special gatherings, or as thoughtful gifts. Each beaded bracelet can be customized with a name or meaningful word (up to 12 characters), making them a unique keepsake for friends, ",
    image: "https://i.etsystatic.com/53294188/r/il/4d2a10/7112755629/il_fullxfull.7112755629_3gul.jpg",
    image2: "https://i.etsystatic.com/53294188/r/il/7c78fc/7695653862/il_fullxfull.7695653862_sfyh.jpg",
    colors: ["White", "Yellow", "Lemon", "Amber", "Orange", "Cream", "Powder Pink", "Light Pink", "Lilac", "Puprle", "Dark Purple", "Red", "Dark Red", "Pink", "Turquoise"],
    sizes: ["6 inches", "6.5 inches", "7 inches", "7.5 inches", "8 inches"],
    minOrder: 1,
    maxOrder: 5000,
  },
  {
    id: 6,
    title: "Custom Name Beaded Bracelet  – Custom for Events & Employee Appreciation - Bulk Order",
    category: "corporate",
    price: 5.0,
    originalPrice: 7.0,
    description: "Handmade Heishi corporate bracelets designed in your brand colors and logo — perfect for corporate gifts, employee appreciation, and team events. Each custom bracelet arrives ready to gift, beautifully packaged, making it effortless to thank your team, clients, or partners in style. Show your brand spirit with personalized bracelets that tell your ",
    image: "https://i.etsystatic.com/53294188/r/il/af99d7/7423406861/il_fullxfull.7423406861_c33r.jpg",
    image2: "https://i.etsystatic.com/53294188/r/il/d994ab/6480727754/il_fullxfull.6480727754_b4dd.jpg",
    colors: ["White", "Yellow", "Lemon", "Amber", "Orange", "Cream", "Powder Pink", "Light Pink", "Lilac", "Puprle", "Dark Purple", "Red", "Dark Red", "Pink", "Turquoise"],
    sizes: ["6 inches", "6.5 inches", "7 inches", "7.5 inches", "8 inches"],
    minOrder: 1,
    maxOrder: 5000,
  },
  {
    id: 7,
    title: "Colorful Name Bracelet | Custom Heishi Beaded Jewelry | Boho Friendship Gift",
    category: "heishi_clay",
    price: 5.0,
    originalPrice: 7.0,
    description: "Custom name heishi bracelet handmade for women — a personalized boho summer jewelry piece designed to celebrate friendship, positivity, and meaningful moments. This colorful heishi bracelet is perfect as a friendship bracelet, summer bracelet, or thoughtful gift for her. Bulk options are available for events and group gifting. Bring sunshine and co",
    image: "https://i.etsystatic.com/53294188/r/il/0e642c/7389188078/il_fullxfull.7389188078_qdro.jpg",
    image2: "https://i.etsystatic.com/53294188/r/il/1449c5/7063191102/il_fullxfull.7063191102_q5lg.jpg",
    colors: ["White", "Yellow", "Lemon", "Amber", "Orange", "Cream", "Powder Pink", "Light Pink", "Lilac", "Puprle", "Dark Purple", "Red", "Dark Red", "Pink", "Turquoise"],
    sizes: ["6 inches", "6.5 inches", "7 inches", "7.5 inches", "8 inches"],
    minOrder: 1,
    maxOrder: 5000,
  },
  {
    id: 8,
    title: "Personalized Beaded Friendship Bracelets – Custom Name Jewelry in Bulk",
    category: "name_bracelets",
    price: 5.0,
    originalPrice: 7.0,
    description: "Celebrate Friendship with Custom Name Bracelets! Looking for a meaningful gift for your friends, team, or loved ones? Our Custom Friendship Bracelets are the perfect way to celebrate connections! Available in bulk quantities (1, 25, 50, 100, 200, or 1000+), each bracelet can be personalized with a name or special word (up to 12 characters), making ",
    image: "https://i.etsystatic.com/53294188/r/il/327716/6528573431/il_fullxfull.6528573431_e2go.jpg",
    image2: "https://i.etsystatic.com/53294188/r/il/8f3c2a/6480467872/il_fullxfull.6480467872_l3ar.jpg",
    colors: ["White", "Yellow", "Lemon", "Amber", "Orange", "Cream", "Powder Pink", "Light Pink", "Lilac", "Puprle", "Dark Purple", "Red", "Dark Red", "Pink", "Turquoise"],
    sizes: ["6 inches", "6.5 inches", "7 inches", "7.5 inches", "8 inches"],
    minOrder: 1,
    maxOrder: 5000,
  },
  {
    id: 9,
    title: "Bulk Faith Bracelet Set – Handmade Christian Jewelry Gift, Bible Verse Favors for Events",
    category: "faith",
    price: 5.0,
    originalPrice: 7.0,
    description: "Celebrate Faith and Friendship in Style! Our Bulk Faith Bracelet Sets are more than accessories — they’re handmade Christian jewelry gifts designed to share love, gratitude, and faith. Whether you’re planning a church event, women’s retreat, or team celebration, these bracelets are a meaningful way to connect hearts. Each bracelet can include your ",
    image: "https://i.etsystatic.com/53294188/r/il/a2f87a/7428271683/il_fullxfull.7428271683_cg2w.jpg",
    image2: "https://i.etsystatic.com/53294188/r/il/a48a3f/7111232467/il_fullxfull.7111232467_93mw.jpg",
    colors: ["Indigo", "Purple", "Magenta", "Fuchsia", "Coral", "Barbie Pink", "Trend Pink", "Pink", "Cream", "Light Pink", "Light Yellow", "Lemon", "Yellow", "Peanut Green", "Green"],
    sizes: ["6 inches", "6.5 inches", "7 inches", "7.5 inches", "8 inches"],
    minOrder: 1,
    maxOrder: 5000,
  },
  {
    id: 10,
    title: "Friendship Bracelet Bulk | Custom Heishi Name Beads | Colorful Handmade | Friend Group Gift",
    category: "heishi_clay",
    price: 5.0,
    originalPrice: 7.0,
    description: "Celebrate friendship, connection, and personal style with this vibrant friendship bracelet designed to add meaning to everyday moments. This playful yet stylish bracelet blends the charm of handmade accessories with the beauty of personalized jewelry, creating a meaningful piece you can wear every day. Each bracelet can be customized to create a un",
    image: "https://i.etsystatic.com/53294188/r/il/b452b0/7424216829/il_fullxfull.7424216829_4xze.jpg",
    image2: "https://i.etsystatic.com/53294188/r/il/b91294/6480913116/il_fullxfull.6480913116_8cls.jpg",
    colors: ["White", "Yellow", "Lemon", "Amber", "Orange", "Cream", "Powder Pink", "Light Pink", "Lilac", "Puprle", "Dark Purple", "Red", "Dark Red", "Pink", "Turquoise"],
    sizes: ["6 inches", "6.5 inches", "7 inches", "7.5 inches", "8 inches"],
    minOrder: 1,
    maxOrder: 5000,
  },
  {
    id: 11,
    title: "Bulk Crystal Bracelet | Custom Name Bracelet | Gemstone Beaded Bracelet | Corporate Gift | Team Bracelet",
    category: "crystal_gemstone",
    price: 5.0,
    originalPrice: 7.0,
    description: "Discover a beautiful crystal bracelet designed to combine elegance, color, and personal meaning. This handcrafted beaded bracelet features carefully selected crystal and gemstone beads, creating a timeless accessory that is stylish yet comfortable for everyday wear. The natural shine of each bead makes this gemstone bracelet a delicate piece that a",
    image: "https://i.etsystatic.com/53294188/r/il/65bcb8/7424104715/il_fullxfull.7424104715_niyi.jpg",
    image2: "https://i.etsystatic.com/53294188/r/il/dec1b2/6753275107/il_fullxfull.6753275107_1mei.jpg",
    colors: ["Off White", "White", "Pink", "Orange", "Red", "Yellow", "Chrome Yellow", "Black", "Light Green", "Green", "Lemon Green", "Leaf Green", "Dark Green", "Baby Blue", "Light Blue"],
    sizes: ["6 inches", "6.5 inches", "7 inches", "7.5 inches", "8 inches"],
    minOrder: 1,
    maxOrder: 5000,
  },
  {
    id: 12,
    title: "Custom Beaded Name Bracelet with Logo Charm – Personalized Bulk Gifts for Teams, Events & Businesses",
    category: "corporate",
    price: 5.0,
    originalPrice: 7.0,
    description: "Make it meaningful with our Custom Beaded Name Bracelet with Engraved Logo Charm A thoughtful and versatile gift for friends, coworkers, and teams, this custom name bracelet blends color, comfort, and personalization in one unique design. Add your own name, initials, or a short word using custom name beads, then complete the look with a gold-plated",
    image: "https://i.etsystatic.com/53294188/r/il/b967e3/7045672087/il_fullxfull.7045672087_kxnb.jpg",
    image2: "https://i.etsystatic.com/53294188/r/il/689cde/6997697348/il_fullxfull.6997697348_440k.jpg",
    colors: ["Indigo", "Purple", "Magenta", "Fuchsia", "Coral", "Barbie Pink", "Trend Pink", "Pink", "Cream", "Light Pink", "Light Yellow", "Lemon", "Yellow", "Peanut Green", "Green"],
    sizes: ["6 inches", "6.5 inches", "7 inches", "7.5 inches", "8 inches"],
    minOrder: 1,
    maxOrder: 5000,
  },
  {
    id: 13,
    title: "Custom Beaded Name Bracelets – Personalized Friendship Party Favor Gifts",
    category: "name_bracelets",
    price: 5.0,
    originalPrice: 7.0,
    description: "Bulk friendship bracelets for parties, birthdays, and team gifts. Personalized name bracelets, handmade with colorful beads for kids or group events. Celebrate every moment with custom beaded bracelets, perfect for kids’ birthdays, party favors, school events, and team gifts. Each bracelet is handmade to order and can be personalized with names or ",
    image: "https://i.etsystatic.com/53294188/r/il/cb6fb7/7695694276/il_fullxfull.7695694276_6hq6.jpg",
    image2: "https://i.etsystatic.com/53294188/r/il/be5adc/7045703071/il_fullxfull.7045703071_3i8q.jpg",
    colors: ["White", "Yellow", "Lemon", "Amber", "Orange", "Cream", "Powder Pink", "Light Pink", "Lilac", "Puprle", "Dark Purple", "Red", "Dark Red", "Pink", "Turquoise"],
    sizes: ["6 inches", "6.5 inches", "7 inches", "7.5 inches", "8 inches"],
    minOrder: 1,
    maxOrder: 5000,
  },
  {
    id: 14,
    title: "Personalized Beaded Bracelet | Handmade with Custom Colors | Fun Gift for Teams & Events | Bulk Order",
    category: "name_bracelets",
    price: 5.0,
    originalPrice: 7.0,
    description: "Looking for a meaningful, fun, and affordable gift for your team, classroom, or event? Our custom name bracelet is the perfect pick! Handmade with love and colorful beads, these bracelets bring joy and connection to every wrist. Whether you need a team gift bracelet, friendship bracelet, or a thoughtful bulk order gift, we’ve got you covered. Custo",
    image: "https://i.etsystatic.com/53294188/r/il/b53af5/7743668573/il_fullxfull.7743668573_15ck.jpg",
    image2: "https://i.etsystatic.com/53294188/r/il/09589a/7045652589/il_fullxfull.7045652589_a8ss.jpg",
    colors: ["Indigo", "Purple", "Magenta", "Fuchsia", "Coral", "Barbie Pink", "Trend Pink", "Pink", "Cream", "Light Pink", "Light Yellow", "Lemon", "Yellow", "Peanut Green", "Green"],
    sizes: ["6 inches", "6.5 inches", "7 inches", "7.5 inches", "8 inches"],
    minOrder: 1,
    maxOrder: 5000,
  },
  {
    id: 15,
    title: "Name Bracelet Bulk | Custom Beaded Personalized | Colorful Handmade | Bridesmaid Team Gift",
    category: "corporate",
    price: 5.0,
    originalPrice: 7.0,
    description: "Celebrate meaningful connections and personal style with this elegant name bracelet designed to add a special touch to everyday moments. Combining the charm of a classic friendship bracelet with the beauty of personalized jewelry, this bracelet is a stylish and heartfelt accessory you can wear daily. Each bracelet can be customized to create a trul",
    image: "https://i.etsystatic.com/53294188/r/il/b478ec/7695746392/il_fullxfull.7695746392_p9ej.jpg",
    image2: "https://i.etsystatic.com/53294188/r/il/290a31/7045588115/il_fullxfull.7045588115_h589.jpg",
    colors: ["Blue", "Dark Blue", "Light Blue", "Turquoise", "Midnight Blue", "Light Fuchsia", "Dark Fuchsia", "Cherry", "Burgundy", "Purple", "Light Purple", "White", "Lilac", "Eggplant Purple", "Metal Pink"],
    sizes: ["6 inches", "6.5 inches", "7 inches", "7.5 inches", "8 inches"],
    minOrder: 1,
    maxOrder: 5000,
  },
  {
    id: 16,
    title: "Beaded Bracelet Bulk | Custom Name Personalized | Colorful Handmade | Graduation Team Gift",
    category: "corporate",
    price: 5.0,
    originalPrice: 7.0,
    description: "Celebrate connection, friendship, and personal style with this elegant bracelet designed to turn simple moments into meaningful memories. Combining the charm of a classic friendship bracelet with the beauty of personalized jewelry, this piece is a stylish accessory that can be worn every day. Each bracelet can be customized to create a truly unique",
    image: "https://i.etsystatic.com/53294188/r/il/2faaf7/7743703415/il_fullxfull.7743703415_6zhd.jpg",
    image2: "https://i.etsystatic.com/53294188/r/il/4741a3/7111249955/il_fullxfull.7111249955_4vv0.jpg",
    colors: ["Indigo", "Purple", "Magenta", "Fuchsia", "Coral", "Barbie Pink", "Trend Pink", "Pink", "Cream", "Light Pink", "Light Yellow", "Lemon", "Yellow", "Peanut Green", "Green"],
    sizes: ["6 inches", "6.5 inches", "7 inches", "7.5 inches", "8 inches"],
    minOrder: 1,
    maxOrder: 5000,
  },
  {
    id: 17,
    title: "Basketball Bracelet Bulk | Custom Player Name | Colorful Handmade | Coach Team Gift",
    category: "team_sports",
    price: 15.99,
    originalPrice: 22.39,
    description: "Celebrate team spirit, friendship, and personal style with this vibrant basketball bracelet designed to add color and meaning to every moment. Featuring a small basketball charm, this playful accessory is perfect for players, fans, and sports lovers who want to carry the spirit of the game wherever they go. Each bracelet is carefully crafted to cre",
    image: "https://i.etsystatic.com/53294188/r/il/1f0bbd/7695444726/il_fullxfull.7695444726_1szw.jpg",
    image2: "https://i.etsystatic.com/53294188/r/il/d78296/6569720967/il_fullxfull.6569720967_3jwe.jpg",
    colors: ["White", "Yellow", "Lemon", "Amber", "Orange", "Cream", "Powder Pink", "Light Pink", "Lilac", "Puprle", "Dark Purple", "Red", "Dark Red", "Pink", "Turquoise"],
    sizes: ["6 inches", "6.5 inches", "7 inches", "7.5 inches", "8 inches"],
    minOrder: 1,
    maxOrder: 5000,
  },
  {
    id: 18,
    title: "Eco-Friendly Personalized Wooden Bracelet – Handmade Sustainable Jewelry Gift for Him & Her",
    category: "eco_friendly",
    price: 5.0,
    originalPrice: 7.0,
    description: "Eco-friendly personalized wooden bracelet made with natural wood beads – a handmade sustainable gift for him or her, perfect for mindful living and everyday style. Bring Nature to Your Wrist Crafted with smooth natural wooden beads, this bracelet combines simplicity, style, and sustainability. Each piece is handmade, polished, and strung with care ",
    image: "https://i.etsystatic.com/53294188/r/il/c70510/7742734715/il_fullxfull.7742734715_i7xm.jpg",
    image2: "https://i.etsystatic.com/53294188/r/il/0d89f9/7742734733/il_fullxfull.7742734733_6fzm.jpg",
    colors: ["White", "Yellow", "Orange", "Red", "Powder Pink", "Lila", "Cherry Rot", "Purple", "Turquoise 1", "Turquoise 2", "Baby Blue", "Blue", "Midnight Blue", "Olive", "Khaki Green"],
    sizes: ["6 inches", "6.5 inches", "7 inches", "7.5 inches", "8 inches"],
    minOrder: 1,
    maxOrder: 5000,
  },
  {
    id: 19,
    title: "Custom Name Beaded Bracelets – Personalized Friendship Jewelry in Bulk for Teams & Schools",
    category: "name_bracelets",
    price: 5.0,
    originalPrice: 7.0,
    description: "Celebrate friendships with our Friendship Bracelets! These stylish beads bracelets are available in bulk quantities, making them the perfect bulk gifts for teams, events, or special occasions. Whether you're looking for bulk jewelry or unique bulk gifts for women, our personalized bracelets add a sentimental touch. Each custom name bracelet can be ",
    image: "https://i.etsystatic.com/53294188/r/il/a951dd/7695046334/il_fullxfull.7695046334_6bif.jpg",
    image2: "https://i.etsystatic.com/53294188/r/il/609105/7695064628/il_fullxfull.7695064628_9s8v.jpg",
    colors: ["White", "Yellow", "Lemon", "Amber", "Orange", "Cream", "Powder Pink", "Light Pink", "Lilac", "Puprle", "Dark Purple", "Red", "Dark Red", "Pink", "Turquoise"],
    sizes: ["6 inches", "6.5 inches", "7 inches", "7.5 inches", "8 inches"],
    minOrder: 1,
    maxOrder: 5000,
  },
  {
    id: 20,
    title: "Corporate Gift Bracelet Bulk | Custom Logo Name | Colorful Handmade | Employee Team Gift",
    category: "corporate",
    price: 5.0,
    originalPrice: 7.0,
    description: "Celebrate meaningful connections and professional appreciation with this elegant custom bracelet designed to combine style with personalization. Blending the look of modern personalized jewelry with timeless design, this bracelet is a versatile accessory perfect for everyday wear or special occasions. Each bracelet can be customized to create a uni",
    image: "https://i.etsystatic.com/53294188/r/il/01a335/7743207361/il_fullxfull.7743207361_bv59.jpg",
    image2: "https://i.etsystatic.com/53294188/r/il/991b3a/7380697206/il_fullxfull.7380697206_cpq1.jpg",
    colors: ["White", "Yellow", "Lemon", "Amber", "Orange", "Cream", "Powder Pink", "Light Pink", "Lilac", "Puprle", "Dark Purple", "Red", "Dark Red", "Pink", "Turquoise"],
    sizes: ["6 inches", "6.5 inches", "7 inches", "7.5 inches", "8 inches"],
    minOrder: 1,
    maxOrder: 5000,
  },
  {
    id: 21,
    title: "Custom Name Bracelet | Handmade Beads in Bulk | Playful & Colorful | Party Favor or Team Gift",
    category: "name_bracelets",
    price: 5.0,
    originalPrice: 7.0,
    description: "Custom name beaded bracelets are fun, colorful, and handmade — the perfect personalized gift for teams, parties, classrooms, and events! Celebrate friendship and creativity with our vibrant designs, made to bring smiles in every bulk order. Each bracelet is crafted with care using soft stretch cord and colorful beads to ensure all-day comfort and d",
    image: "https://i.etsystatic.com/53294188/r/il/2f59f9/7695540544/il_fullxfull.7695540544_sbk0.jpg",
    image2: "https://i.etsystatic.com/53294188/r/il/cfaee2/7695545022/il_fullxfull.7695545022_lb88.jpg",
    colors: ["Indigo", "Purple", "Magenta", "Fuchsia", "Coral", "Barbie Pink", "Trend Pink", "Pink", "Cream", "Light Pink", "Light Yellow", "Lemon", "Yellow", "Peanut Green", "Green"],
    sizes: ["6 inches", "6.5 inches", "7 inches", "7.5 inches", "8 inches"],
    minOrder: 1,
    maxOrder: 5000,
  },
  {
    id: 22,
    title: "Seed Bead Bracelet Bulk | Personalized Name Colors | Boho Handmade Style | Bridesmaid Gift",
    category: "seed_bead",
    price: 5.0,
    originalPrice: 7.0,
    description: "Celebrate friendship, style, and personal expression with this colorful seed bead bracelet designed to add charm and meaning to every day. This vibrant bracelet combines the playful look of a classic friendship bracelet with the elegance of personalized jewelry, making it a stylish and meaningful accessory for everyday wear. Each bracelet can be cu",
    image: "https://i.etsystatic.com/53294188/r/il/41925c/6529089675/il_fullxfull.6529089675_td4y.jpg",
    image2: "https://i.etsystatic.com/53294188/r/il/31c93d/7695556594/il_fullxfull.7695556594_qmgv.jpg",
    colors: ["Indigo", "Purple", "Magenta", "Fuchsia", "Coral", "Barbie Pink", "Trend Pink", "Pink", "Cream", "Light Pink", "Light Yellow", "Lemon", "Yellow", "Peanut Green", "Green"],
    sizes: ["6 inches", "6.5 inches", "7 inches", "7.5 inches", "8 inches"],
    minOrder: 1,
    maxOrder: 5000,
  },
  {
    id: 23,
    title: "Christian Heishi Bracelet | Faith Bulk Gift for Church & Youth Groups | Bible Verse Beaded Jewelry",
    category: "faith",
    price: 5.0,
    originalPrice: 7.0,
    description: "Make your gift meaningful with our faith bracelet – a colorful heishi bracelet personalized with names, Bible verses, or Christian words. Whether you're planning a youth group gift, a church retreat gift, or a Christian gift for a loved one, this custom name bracelet is made to inspire. These handmade bracelets are crafted with vibrant Heishi beads",
    image: "https://i.etsystatic.com/53294188/r/il/2bdc92/7064867422/il_fullxfull.7064867422_nofx.jpg",
    image2: "https://i.etsystatic.com/53294188/r/il/f1953c/7695553872/il_fullxfull.7695553872_t6h2.jpg",
    colors: ["White", "Yellow", "Lemon", "Amber", "Orange", "Cream", "Powder Pink", "Light Pink", "Lilac", "Puprle", "Dark Purple", "Red", "Dark Red", "Pink", "Turquoise"],
    sizes: ["6 inches", "6.5 inches", "7 inches", "7.5 inches", "8 inches"],
    minOrder: 1,
    maxOrder: 5000,
  },
  {
    id: 24,
    title: "Custom Name Beaded Bracelets | Personalized Bulk Gifts for Teams, Events, Classrooms & Friendship Groups",
    category: "name_bracelets",
    price: 5.0,
    originalPrice: 7.0,
    description: "Celebrate connection, creativity, and team spirit with our Custom Name Beaded Bracelets —handcrafted in bulk for classrooms, teams, events, and friendships. Each bracelet is handmade by our 14-women artisan team using durable stretch cord and colorful beads. Add a name, word, or number (up to 12 characters) to create a heartfelt gift your group wil",
    image: "https://i.etsystatic.com/53294188/r/il/2df78d/7435208313/il_fullxfull.7435208313_o8mo.jpg",
    image2: "https://i.etsystatic.com/53294188/r/il/5e4735/6768339260/il_fullxfull.6768339260_stcr.jpg",
    colors: ["White", "Yellow", "Lemon", "Amber", "Orange", "Cream", "Powder Pink", "Light Pink", "Lilac", "Puprle", "Dark Purple", "Red", "Dark Red", "Pink", "Turquoise"],
    sizes: ["6 inches", "6.5 inches", "7 inches", "7.5 inches", "8 inches"],
    minOrder: 1,
    maxOrder: 5000,
  },
  {
    id: 25,
    title: "Custom Name Bracelet Bulk | Seed Bead Personalized | Boho Colorful Handmade | Gift for Her",
    category: "seed_bead",
    price: 5.0,
    originalPrice: 7.0,
    description: "Celebrate friendship, color, and personal style with this vibrant seed bead bracelet designed to bring meaning to everyday moments. This playful accessory combines the charm of a classic friendship bracelet with the beauty of personalized jewelry, creating a stylish piece that is lightweight, comfortable, and perfect for daily wear. Each bracelet c",
    image: "https://i.etsystatic.com/53294188/r/il/184d15/7437038735/il_fullxfull.7437038735_jsmg.jpg",
    image2: "https://i.etsystatic.com/53294188/r/il/6bb5a9/7389119524/il_fullxfull.7389119524_bwpb.jpg",
    colors: ["Indigo", "Purple", "Magenta", "Fuchsia", "Coral", "Barbie Pink", "Trend Pink", "Pink", "Cream", "Light Pink", "Light Yellow", "Lemon", "Yellow", "Peanut Green", "Green"],
    sizes: ["6 inches", "6.5 inches", "7 inches", "7.5 inches", "8 inches"],
    minOrder: 1,
    maxOrder: 5000,
  },
  {
    id: 26,
    title: "Custom Name Bracelet | Bold Color Options | Modern Handmade Style | Corporate Gift or Team Giveaway",
    category: "corporate",
    price: 5.0,
    originalPrice: 7.0,
    description: "Celebrate connection, color, and creativity with our Custom Name Beaded Bracelets – the perfect personalized bracelet gift for events, friends, and school teams! Whether you’re planning a birthday party, organizing a classroom celebration, or prepping gifts for a team or corporate event, these beaded name bracelets are crafted to make every recipie",
    image: "https://i.etsystatic.com/53294188/r/il/865501/7590569526/il_fullxfull.7590569526_o346.jpg",
    image2: "https://i.etsystatic.com/53294188/r/il/94768a/7695567954/il_fullxfull.7695567954_ahf2.jpg",
    colors: ["Off White", "White", "Pink", "Orange", "Red", "Yellow", "Chrome Yellow", "Black", "Light Green", "Green", "Lemon Green", "Leaf Green", "Dark Green", "Baby Blue", "Light Blue"],
    sizes: ["6 inches", "6.5 inches", "7 inches", "7.5 inches", "8 inches"],
    minOrder: 1,
    maxOrder: 5000,
  },
  {
    id: 27,
    title: "Personalized Name Beaded Bracelets – Handmade Friendship Jewelry for Teams & Friends",
    category: "heishi_clay",
    price: 5.0,
    originalPrice: 7.0,
    description: "The Perfect Personalized Gift – Custom Name Bracelets! Make your loved ones feel special with handmade beaded bracelets customized just for them! These Personalized Friendship Bracelets are perfect for birthdays, holidays, and group events. Customize with names, initials, or a special word for a unique keepsake they’ll cherish forever. Why Choose O",
    image: "https://i.etsystatic.com/53294188/r/il/eb582d/7695573178/il_fullxfull.7695573178_oieh.jpg",
    image2: "https://i.etsystatic.com/53294188/r/il/855740/7063176440/il_fullxfull.7063176440_e7ra.jpg",
    colors: ["White", "Yellow", "Lemon", "Amber", "Orange", "Cream", "Powder Pink", "Light Pink", "Lilac", "Puprle", "Dark Purple", "Red", "Dark Red", "Pink", "Turquoise"],
    sizes: ["6 inches", "6.5 inches", "7 inches", "7.5 inches", "8 inches"],
    minOrder: 1,
    maxOrder: 5000,
  },
  {
    id: 28,
    title: "Gratitude Bracelet Bulk | Personalized Seed Bead | Colorful Handmade | Self Care Gift for Her",
    category: "seed_bead",
    price: 5.0,
    originalPrice: 7.0,
    description: "Celebrate meaningful connections and everyday beauty with this elegant beaded bracelet designed to bring a delicate and stylish touch to your jewelry collection. This lightweight dainty bracelet is carefully crafted to create a timeless bracelet for women that feels comfortable for daily wear while still looking elegant and special. Each bracelet i",
    image: "https://i.etsystatic.com/53294188/r/il/60786d/7388018420/il_fullxfull.7388018420_jb47.jpg",
    image2: "https://i.etsystatic.com/53294188/r/il/75dd46/6773728827/il_fullxfull.6773728827_gcvu.jpg",
    colors: ["Indigo", "Purple", "Magenta", "Fuchsia", "Coral", "Barbie Pink", "Trend Pink", "Pink", "Cream", "Light Pink", "Light Yellow", "Lemon", "Yellow", "Peanut Green", "Green"],
    sizes: ["6 inches", "6.5 inches", "7 inches", "7.5 inches", "8 inches"],
    minOrder: 1,
    maxOrder: 5000,
  },
  {
    id: 29,
    title: "Custom Name Beaded Bracelets | Bulk Personalized Friendship Jewelry for Kids & Teams",
    category: "name_bracelets",
    price: 5.0,
    originalPrice: 7.0,
    description: "Personalized name beaded bracelets made for kids, schools, teams & events – handcrafted in bulk with custom words & real beads. Celebrate connection, color, and creativity with our personalized beaded name bracelets — handcrafted in bulk by our 14-women artisan team for schools, teams, and special events. Each bracelet is made with premium crystal ",
    image: "https://i.etsystatic.com/53294188/r/il/16b71d/6609778655/il_fullxfull.6609778655_ajy2.jpg",
    image2: "https://i.etsystatic.com/53294188/r/il/d7bbbb/6609778647/il_fullxfull.6609778647_hul8.jpg",
    colors: ["White", "Yellow", "Lemon", "Amber", "Orange", "Cream", "Powder Pink", "Light Pink", "Lilac", "Puprle", "Dark Purple", "Red", "Dark Red", "Pink", "Turquoise"],
    sizes: ["6 inches", "6.5 inches", "7 inches", "7.5 inches", "8 inches"],
    minOrder: 1,
    maxOrder: 5000,
  },
  {
    id: 30,
    title: "Custom Heishi Beaded Name Bracelets in Bulk, Personalized Fimo Friendship Jewelry for Girls, Party Favors, School Gifts, Handmade",
    category: "heishi_clay",
    price: 5.0,
    originalPrice: 7.0,
    description: "Celebrate friendship and connection with our handmade custom name bracelets — perfect as bulk friendship gifts for schools, events, or teams 💕 Whether it’s a birthday, spirit day, or a meaningful thank-you, these heishi bead bracelets offer a fun and personal way to show you care. Each beaded name bracelet is handmade by our all-women team using hi",
    image: "https://i.etsystatic.com/53294188/r/il/d93964/6528739859/il_fullxfull.6528739859_crbh.jpg",
    image2: "https://i.etsystatic.com/53294188/r/il/9edd49/6480635580/il_fullxfull.6480635580_lvwl.jpg",
    colors: ["White", "Yellow", "Lemon", "Amber", "Orange", "Cream", "Powder Pink", "Light Pink", "Lilac", "Puprle", "Dark Purple", "Red", "Dark Red", "Pink", "Turquoise"],
    sizes: ["6 inches", "6.5 inches", "7 inches", "7.5 inches", "8 inches"],
    minOrder: 1,
    maxOrder: 5000,
  },
  {
    id: 31,
    title: "Colorful Name Beaded Bracelets – Custom Friendship Gifts for Groups & Parties",
    category: "heishi_clay",
    price: 5.0,
    originalPrice: 7.0,
    description: "Celebrate meaningful connections with our Personalized Friendship Bracelets! Each Custom Name Bracelet is fully customizable—add names, initials, or a special message to create a unique Personalized Bracelet. These stylish Bead Bracelets are perfect for Friendship Gifts, Team Bracelets, or Bulk Gifts, making every occasion even more special. Whethe",
    image: "https://i.etsystatic.com/53294188/r/il/467964/7743578623/il_fullxfull.7743578623_ly6o.jpg",
    image2: "https://i.etsystatic.com/53294188/r/il/c205f2/7130087821/il_fullxfull.7130087821_3hz3.jpg",
    colors: ["White", "Yellow", "Lemon", "Amber", "Orange", "Cream", "Powder Pink", "Light Pink", "Lilac", "Puprle", "Dark Purple", "Red", "Dark Red", "Pink", "Turquoise"],
    sizes: ["6 inches", "6.5 inches", "7 inches", "7.5 inches", "8 inches"],
    minOrder: 1,
    maxOrder: 5000,
  },
  {
    id: 32,
    title: "Custom Beaded Name Bracelets – Personalized Team & Event Jewelry in Bulk",
    category: "name_bracelets",
    price: 5.0,
    originalPrice: 7.0,
    description: "Celebrate your unique style with our custom bracelet collection! From team bracelets to bead bracelets, our pieces are perfect for bridesmaid gifts, bulk gifts, and personalized gifts. Add a personal touch with a custom name bracelet or custom beads for a meaningful friendship gift. These handmade gifts are also great party favors and unique jewelr",
    image: "https://i.etsystatic.com/53294188/r/il/41e618/6605439015/il_fullxfull.6605439015_ep42.jpg",
    image2: "https://i.etsystatic.com/53294188/r/il/ae52d9/7110090461/il_fullxfull.7110090461_srhg.jpg",
    colors: ["Indigo", "Purple", "Magenta", "Fuchsia", "Coral", "Barbie Pink", "Trend Pink", "Pink", "Cream", "Light Pink", "Light Yellow", "Lemon", "Yellow", "Peanut Green", "Green"],
    sizes: ["6 inches", "6.5 inches", "7 inches", "7.5 inches", "8 inches"],
    minOrder: 1,
    maxOrder: 5000,
  }
];
